name: epubx
description: Epub Parser for Dart. Epub package fork. Suitable for use on the Server, the Web, or in Flutter
homepage: https://github.com/rbcprolabs/epubx.dart
issue_tracker: https://github.com/rbcprolabs/epubx.dart
version: 3.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"
#  sdk: '>=2.19.4 <3.0.0'

#dependencies:
#  archive: ^3.3.7
#  quiver: ^3.2.1
##  xml: ^6.3.0
#  xml: 6.0.1
#  image: ^4.0.16
#  collection: 1.17.0

dependencies:
  archive: ^3.1.2
  quiver: ^3.0.0
  xml: ^6.1.0
  image: ^3.0.2
  collection: ^1.15.0


#dependency_overrides:
#  meta: ^1.9.1


dev_dependencies:
  test: ^1.24.2
  path: ^1.8.3
  lints: ^2.0.1
